from robo.task.synthetic_functions.branin import Branin
from robo.task.synthetic_functions.hartmann3 import Hartmann3
from robo.task.synthetic_functions.hartmann6 import Hartmann6
from robo.task.synthetic_functions.goldstein_price import GoldsteinPrice
from robo.task.synthetic_functions.levy import Levy
from robo.task.synthetic_functions.bohachevsky import Bohachevsky
from robo.task.synthetic_functions.rosenbrock import Rosenbrock
from robo.task.synthetic_functions.camelback import Camelback
from robo.task.synthetic_functions.sin import SinOne
from robo.task.synthetic_functions.sin import SinTwo